photos/urls.py
from django.conf.urls import url
from . import views

app_name = 'photos'

urlpatterns = [
    #url(r'^test/$', views.test),
    url(r'^new/$', views.create_post, name='create'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete_post, name='delete'),
    url(r'^(?P<pk>\d+)/$', views.view_post, name='view'),
    url(r'^$', views.list_posts, name='list'),
    url(r'^comments/(?P<pk>[0-9]+)/$', views.delete_comment, name='delete_comment'),
    url(r'^temp/$', views.temp, name='temp'),
    #url(r'', views.list_posts, name='redirect'),
]

pystagram/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from rest_framework import routers

from photos.views import PostViewSet

router = routers.DefaultRouter()
router.register(r'photos', PostViewSet)

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login_page',),
    url(r'^logout/$', logout, {'next_page': settings.LOGIN_URL }),
    url(r'^photos/',include('photos.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns.append(
    url(r'',include('social.apps.django_app.urls', namespace='social'))
)

photos/models.py
from django.db import models
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=40)
    parent = models.ForeignKey('self', null=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False)
    category = models.ForeignKey(Category, null=True, blank=True)
    title = models.CharField(max_length=50, null=False, blank=False)
    content = models.TextField(null=False, blank=False)
    image = models.ImageField(upload_to='%Y/%m/%d/', null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    # Tag모델 자체가 밑에서 선언되어 NameError 발생
    # 모델이름을 직접 입력하는데 아닌 모델의 Name Space를 넣어 충돌 방지
    # NameSpace로 넘어갈 경우 모델을 만들며 바로 관계를 맺지 않음
    # 모든 모델을 다 생성 한후 그 이후에 관계를 맺어 충돌을 방지합니다.
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    likes = GenericRelation('Like2')

    class Meta:
        ordering = ['-created_at', '-id']

    def __str__(self):
#        return '{}'.format(self.pk)
        return str(self.pk)

    def get_absolute_url(self):
        return reverse_lazy('photos:view', kwargs={'pk': self.pk})

#    def delete(self, *args, **kwargs):
#        super(Post, self).delete(*args, **kwargs)
#        self.image.delete(save=False)
# QuerySet으로 들어갈 경우[ex) filter ]에는 작동이 안됨 , 때문에 signal이 안전함

    class Meta:
        ordering = ['-updated_at']
        permissions = (("delete_post_perm", "Delete Post"),)

        permissions = (
        ("can_delete_post","delete post"),
        )


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    likes = GenericRelation('Like2')


    class Meta:
        ordering = ['-created_at']

class Tag(models.Model):
    name = models.CharField(max_length= 40)

    def __str__(self):
        return self.name

class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    post = models.ForeignKey(Post)
    created_at = models.DateTimeField(auto_now_add=True)

class Like2(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

photos/forms.py
from django import forms
from django.forms import ValidationError
from .models import Post
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class PostForm(forms.ModelForm):
    tagtext = forms.CharField(required=False)
    class Meta:
        model = Post
        fields = ('category','image', 'title', 'content',)

    def clean_content(self):
        content = self.cleaned_data['content']
        if '바보' in content:
            raise ValidationError("금지어가 있습니다.")
        return content

class SimpleForm(forms.Form):
    title = forms.CharField(min_length =3, max_length= 10)
    content = forms.CharField(widget=forms.Textarea)

photos/views.py
import os
import logging

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from django.http import HttpResponseBadRequest
from django.http import HttpResponseRedirect
from django.http import HttpResponsePermanentRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Permission
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.exceptions import PermissionDenied
from django.core import serializers
from django.conf import settings
from django.db import transaction
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from rest_framework import serializers as drf_serializers
from rest_framework import viewsets

from .models import Post
from .models import Tag
from .models import Comment
from .models import Like
from .forms import PostForm
from .forms import CommentForm
from pystagram.sample_exceptions import HelloWorldError


logger = logging.getLogger('django')
formatter = logging.Formatter('%(asctime)s- %(name)s - %(levelname)s - %(message)s')

import base64


def get_base64_image(data):
    if data is None or ';base64,' not in data:
        return None

    _format, _content = data.split(';base64,')
    return base64.b64decode(_content)


@login_required
def create_post(request):
    if request.method == 'GET':
        form = PostForm()
    elif request.method == 'POST':
        filtered = request.POST.get('filtered_image')
        if filtered:
            filtered_image = get_base64_image(filtered)
            filename = request.FILES['image'].name.split(os.sep)[-1]
            _filedata = {
                'image': SimpleUploadedFile(
                    filename, filtered_image
                )
            }
        else:
            _filedata = request.FILES

        form = PostForm(request.POST, _filedata)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            tag_text = form.cleaned_data.get('tagtext', '')
            tags = tag_text.split(',')
            for _tag in tags:
                _tag = _tag.strip()
                tag, _ = Tag.objects.get_or_create(name=_tag, defaults={'name': _tag})
                post.tags.add(tag)

            return redirect('photos:view', pk=post.pk)

    ctx = {
        'form': form,
    }
    return render(request, 'edit_post.html', ctx)


#class PostCreateView(CreateView):
#    model = Post
#    form_class = PostForm
#    template_name = 'edit_post.html'


#create_post = PostCreateView.as_view()



def list_posts(request):
#    logger.warning("경고 경고")
#    raise HelloWorldError("뭔가 문제가 있다")
    page = request.GET.get('page', 1)
    per_page = 2

    posts = Post.objects\
                    .all()\
    #                .order_by('-created_at', '-pk')
    # Model에 Meta클래스에 ordering항목으로 대체할 수 있음

    pg = Paginator(posts, per_page)
    try:
        contents = pg.page(page)
    except PageNotAnInteger:
        contents = pg.page(1)
    except EmptyPage:
        contents = []

    # unique값이 없기 때문에 같은 시간에 값이 입력이 될 수 있음
    # 똑같은 값의 데이터가 있을때의 2번째의 인자인 pk값으로 차순위 정렬이 됨
    if request.is_ajax():
        data = serializers.serialize('json', contents)
        return HttpResponse(data)

    ctx = {
        'posts': contents,
        }

    return render(request, 'list.html', ctx)

#class PostListView(ListView):
#    model = Post
#    context_object_name = 'posts'
#    template_name = 'list.html'
#    paginate_by = 2
    # queryset = Post.objects.all().order_by('-created_at')

#    def get_queryset(self):
#        return Post.objects.order_by('-created_at')

#list_posts = PostListView.as_view()

@login_required
#@cache_page(60 * 5)
def view_post(request, pk):
    key = 'post_object_{}'.format(pk)
    post =cache.get(key)
    if not post:
        post = Post.objects.get(pk=pk)
        cache.set(key, post, 300)
        print('get data form db')
    else:
        print('get cached data')
    #post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    if request.method == "GET":
        form = CommentForm()
    elif request.method == "POST":
        if not request.user.is_authenticated():
            return redirect(settings.LOGIN_URL)
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect(post)# Post모델의 'get_absolute_url()'메서드를 호출해서 가능


    ctx = {
        'post':post,
        'comment_form': form
    }
    return render(request, 'view.html', ctx)

@login_required
def delete_post(request, pk):
#    if request.method != "POST" and not request.user.id == Post.objects.get(pk=pk).user.pk:
#        return redirect(settings.LOGIN_URL)
    #print()
    #print(Post.objects.get(pk=pk).user.id)
    #if not request.user.is_authenticated:
        #return redirect(settings.LOGIN_URL)
#    print("owner",post_owner)
#    print("request_user",request.user)
    if request.method =="GET":
        return render(request, "bad_request.html")
    else:
        if not request.user == Post.objects.get(id=pk).user:
        #or not request.user.id == Post.objects.get(pk=pk).user.id:
            raise PermissionDenied
        else:
            post = get_object_or_404(Post, pk=pk)
            post.delete()

            #return HttpResponsePermanentRedirect('photos:list')
            #return render(request, 'list.html', status=302)
            return redirect('photos:list')
    #else:
        #return render(request, 'notgoodget.html')


def delete_comment(request, pk):
    if request.method != "POST":
        return HttpResponseBadRequest()
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()

    return redirect(comment.post)


def temp(request):
    return redirect('photos:list')

@login_required
def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method != "POST":
        raise Exception('bad request')

    qs = post.like_set.filter(user=request.user)
    if qs.exists():
        like = qs.get()
        like.delete()
    else:
        like = Like()
        like.post = post
        like.user = request.user
        like.save()

    return redirect(post)


class PostSerializer(drf_serializers.ModelSerializer):
    class Meta:
        model = Post
        fields = ('image', 'content', )
class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

photos/templates/edit_post.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 편집{% endblock %}

{% block body %}

<form method="POST" id="form-post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="filtered_image" />
    {# {{ form.as_p }} #}

    <div id="filter_nav">
        <p><img src="" id="preview" /></p>
        <button value="vintage">Vintage</button>
        <button value="sepia">Sepia</button>
    </div>

    {% bootstrap_form form %}

    <p>
        <button type="submit" class="btn btn-primary btn-lg">
            {% bootstrap_icon "star" %} 저장</button>
    </p>
</form>

{% endblock %}

photos/templates/layout.html
{% load bootstrap3 %}
{% load static from staticfiles %}
{% load cache %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block page_title %}Pystagram{% endblock %}</title>
        {% cache 3600 scripts_tags %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script src="{% static 'vintageJS/dist/jquery.vintage.min.js' %}"></script>
        <script src="{% static 'vintageJS/vintage.presets.js' %}"></script>
        <script src="{% static 'hello.js' %}"></script>
        {% endcache %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    </head>

    <body class="container">
        <p>{{ request.just_say }}</p>
        {% block body %}{% endblock %}
    </body>
</html>

photos/templates/list.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 목록 페이지{% endblock %}

{% block body %}
<div>
    <h1>사진 목록</h1>

    {% for post in posts %}
    <div class="photo_container">
        <a href="{% url 'photos:view' pk=post.pk %}">
            {% if post.image %}
                <p><img src={{ post.image.url }} /></p>
            {% endif %}
        </a>
        <a href="{% url 'photos:view' pk=post.pk %}"><p>{{ post.content }}</p>
        </a>
        <p>
        <a href="{% url 'photos:view' pk=post.pk %}">{{ post.created_at }}</a>
        </p>
    </div>
    {% empty %}
    <p>게시물이 없습니다.</p>
    {% endfor %}
    {#    {% bootstrap_pagination page_obj %} #}

</div>

{% endblock %}

photos/templates/view.html
{% extends 'layout.html' %}
{% load my_tags %}
{% load bootstrap3 %}
{% load cache %}

{% block page_title %}글 보기{% endblock %}

{% block body %}

{% autoescape off %}
{% helloworld "first" "second" kwd1="1" kwd2="2" %}
{% endautoescape %}

<div style="border: 1px solid #000;">
{% addnim %}
<p>현재 이용자 : {{ request.user }}</p>
<p>작성자 : {{ post.user }}</p>
{% end_add_nim %}
</div>


<h3>{{ post.pk }}번 사진</h3>

{% if post.image %}
<p><img src="{{ post.image.url }}" /></p>
{% endif %}

<div>{{ post.content }}</div>

<p>
    {{ post.created_at }}
</p>
<p>
    {% if post|did_like:request.user %}
    좋아요 취소
    {% else %}
    좋아요
    {% endif %}
</p>
<hr/>
{% for comment in post.comment_set.all %}
    <div>
    <!---    <p>{{ comment.pk }}</p> --->
        <p>{{ comment.content }}</p>
        <p style="color:blue;">{{ comment.user.username }}</P>
        <form method="POST" action="{% url 'photos:delete_comment' pk=comment.pk %}">
            {% csrf_token %}
            <button type="submit">댓글 삭제</button>
        </form>
    </div>
{% empty %}
    <p>댓글이 없습니다.</p>
{% endfor %}

<form method="POST" action="">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <p>
        <button type="submit" class="btn btn-primary btn-lg">
            {% bootstrap_icon "star" %} 저장</button>
    </p>
</form>


{% endblock %}